edera-dev/krata

release-plz.toml
- fix release and tag names so that it is v{{ version }}, which will get rid of the problem with v${version} being created.
- don't semver check lower-level crates, since those are not actually public API
=> ci: workflow and release process improvements

.github/workflows/release-plz.yml
release PRs aren't running status checks because github-actions issued GITHUB_TOKENs mask all new events, in order to prevent loops. We don't care about loops, because the PR merge prevents the loop for happening.
=> fix: release pr trigger problem

resources/openrc/kratad, resources/openrc/kratanet, resources/systemd/kratanet.service
the service files don't make kratanet depend on kratad, which is fine normally since kratanet will restart when kratad isn't available, but it is probably better to declare the dependency.
in addition, we also remove the dependency on xenconsoled in OpenRC, since we don't depend on that daemon anymore.
=> fix: service files should have kratanet depend on kratad

.github/workflows/check.yml, .github/workflows/client.yml, .github/workflows/kernel.yml, .github/workflows/os.yml, .github/workflows/release-plz.yml, .github/workflows/server.yml
- use the cultivation bot to push release changes, so that workflows will run when a force-push is used and the PR is already created.
- check/lint workflows should run on merge queue and on pull requests, and no more than that.
- nightly build is still responsible for doing a full main rebuild every night.
=> chore: release workflow fixes to improve utilization and fix checks

.github/workflows/client.yml, .github/workflows/kernel.yml, .github/workflows/nightly.yml, .github/workflows/os.yml, .github/workflows/release-binaries.yml, .github/workflows/release-plz.yml, .github/workflows/server.yml
- prefix all jobs with the name of the workflow, to distinguish things in the UI
- release-plz should cancel in progress jobs to prevent double release during merge queue
=> chore(workflows): improve workflow setup

hack/build/cargo.sh, hack/build/target.sh
The Alpine Rust toolchain uses `-alpine-linux-musl` for years while the upstream Rust toolchain still does not have support for dynamic linking (despite musl supporting dynamic linking since the beginning of the rust port).
=> fix: use alpine rust triplets when building on alpine

crates/guest/src/init.rs
Most terminal emulators support the xterm control codes more faithfully than the vt100 ones.
Fixes #51.
=> guest: init: default to xterm if TERM is not set

hack/debug/common.sh
doas sudo shim (as used by Alpine) does not support passing through environment variables in the same way that sudo does, therefore use `sh -c` instead.
=> debug: common: run programs in a way that is compatible with alpine doas-sudo-shim

Cargo.toml, hack/initrd/build.sh
before:
```
-rwxr-xr-x  1 kaniini kaniini 7.5M Apr 13 01:28 init
```
after:
```
-rwxr-xr-x 2 kaniini kaniini 4.5M Apr 13 01:44 init
```
or, in other words, a ~40% reduction in guestinit!
=> build: use LTO for release builds and strip guestinit

crates/ctl/src/cli/idm_snoop.rs, crates/ctl/src/cli/mod.rs, crates/daemon/src/control.rs, crates/daemon/src/idm.rs, crates/krata/build.rs, crates/krata/proto/krata/bus/idm.proto, crates/krata/proto/krata/v1/control.proto, crates/krata/src/bus/idm.rs, crates/krata/src/bus/mod.rs, crates/krata/src/idm/client.rs, crates/krata/src/idm/mod.rs, crates/krata/src/lib.rs
Implement IDM snooping, a new feature that lets you snoop on messages between guests and the host. The feature exposes the IDM packets send and receives to the API, allowing kratactl to now listen for messages and feed them to a user for debugging purposes.
This PR fixes #67
=> feat: idm snooping

crates/oci/src/packer/cache.rs
fs::rename won't work for cross-device moves (oops)
now, we attempt rename, if that fails then we fallback to a copy and remove.
rename is still used because it prevents us from paying the cost of a copy if it's possible to avoid.
=> fix: oci cache store should fallback to copy when rename won't work

DEV.md
This change corrects the steps order to have the krata daemon started before starting the krata networking service
=> docs(dev): update order of setup instructions

Cargo.lock, crates/ctl/src/cli/launch.rs, crates/daemon/Cargo.toml, crates/daemon/src/control.rs, crates/daemon/src/lib.rs, crates/daemon/src/reconcile/guest/mod.rs, crates/daemon/src/reconcile/guest/start.rs, crates/krata/proto/krata/v1/common.proto, crates/oci/src/fetch.rs, crates/oci/src/name.rs, crates/oci/src/packer/cache.rs, crates/oci/src/packer/service.rs, crates/oci/src/registry.rs, crates/runtime/src/launch.rs, crates/runtime/src/lib.rs, crates/xen/xenclient/examples/boot.rs, crates/xen/xenclient/src/elfloader.rs, crates/xen/xenclient/src/lib.rs
- kernel images can now be used to specify a kernel by packing an OCI Image with a "kernel/image" file.
- initrd image can now be used to specify an initrd by packing an OCI Image with a "krata/initrd" file.
=> feat: implement kernel / initrd oci image support

DEV.md
This fixes the dev guide to mention copying kernel addons.
=> fix: dev guide should mention copying kernel addons (fixes #125)

Cargo.lock, crates/xen/xencall/src/lib.rs, crates/xen/xenclient/Cargo.toml, crates/xen/xenclient/src/lib.rs, crates/xen/xenclient/src/pci.rs
currently, there are multiple transactions when setting up devices in xenclient, with this, there is a single commit.
=> fix(xenclient): use a single transaction for device setup

crates/daemon/src/reconcile/guest/start.rs
the addons.squashfs file often is fairly large due to the GPU modules containing a lot of code
I don't consider the file limit important anymore, and I would argue it's imposed at the wrong layer anyways.
=> fix(oci): remove file size limit

crates/oci/src/name.rs
docker hub rate limits, and since we don't yet have support for repository secrets (coming soon!) it's safe to just swap.
=> fix(oci): use mirror.gcr.io as a mirror to docker hub

.github/workflows/check.yml, .github/workflows/client.yml, .github/workflows/kernel.yml, .github/workflows/nightly.yml, .github/workflows/os.yml, .github/workflows/release-binaries.yml, .github/workflows/release-plz.yml, .github/workflows/server.yml
Pin GitHub Actions to a digest to [prevent supply chain attacks](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions). Adds Step Security Github Actions Harden Runner agent, which monitors for least privilege GITHUB_TOKEN permissions and egress connections. More info [here](https://github.com/step-security/harden-runner)
=> chore: pin actions to digests and introduce step security hardened runners

crates/daemon/src/lib.rs, crates/runtime/src/ip.rs, crates/runtime/src/launch.rs, crates/runtime/src/lib.rs
Previously, krata runtime allowed a single permit when performing operations. This was necessary because the only IP allocation storage was xenstore, and the commit of xenstore data happens after allocation. This commit introduces IpVendor, a service which vends IPv4 and IPv6 addresses to guests using a linear address strategy within an IP network space. The IpVendor table is initialized from xenstore, and from there on out, the in-memory table is the source of truth. This implementation is not perfect, but it will allow us to lift the single permit limit, allowing guests to start concurrently.
=> feat(runtime): concurrent ip allocation

.github/dependabot.yml
We have a need to ensure great security while also ensuring that dependabot does not constantly provide multiple PRs. After all, when something becomes too time consuming it risks not being handled with care. With grouped updates, version bumps will get grouped together, but security updates will still be indvidualized. This makes it safer for us to enable grouped dependency updates.
=> chore(dependabot): group some dependency updates

hack/os/build.sh
The resolv.conf that the stage1 os script generates is fine for actual use, but our GitHub workflows now uses the Step Security hardened runner action. This action replaces the nameserver so that all lookups go through that, but because the chroot calls apk add, it needs to contact the internet. On the GitHub workflows, the OS build currently fails since the hardened runner cannot access other nameservers.
=> fix(build): use host resolv.conf in os build chroot

hack/kernel/fetch.sh
The kernel fetch script should build use the host target at all times.
=> fix(build): kernel fetch should use host target

os/internal/stage2.sh
There is currently a bug in the Xen support for Alpine where /boot/config-lts is expected to exist but in Alpine /boot/config-VERSION-lts is the only file available. This change copies the config to /boot/config-lts to fix the build.
=> fix(os): alpine v3.20 requires copying kernel config before grub-mkconfig

crates/daemon/bin/daemon.rs, crates/daemon/src/event.rs, hack/debug/common.sh
This change adds the ability for the Krata daemon to send log events to fluentd over TCP. This change creates a few pieces of technical debt:
- stdout logging is disabled when pushing to fluentd. This is because env-logger doesn't support parallel sinks.
- only TCP is supported at the moment, and there is no ability for it to reconnect to fluentd should the stream die without restarting the daemon
In addition to addressing the above, this work has highlighted the following future improvements:
- We should be using structured logging
- We should use a log crate that supports parallel sinks
- We need to aggregate logs across components over IDM before exporting
- We need to expose the ability to fine tune the o11y configuration
=> Initial fluentd support

.github/workflows/oci-distribution.yml, images/Dockerfile.kratactl, images/Dockerfile.kratad, images/Dockerfile.kratanet
This is for enabling OCI-based distribution of the OSS components included in the Edera Protect distribution.
=> OCI distribution

crates/daemon/src/event.rs, crates/runtime/src/power.rs
Xeon machines were being mis-detected a P/E compatible, as well as a crash occurring due to overflow during subtraction. This fixes that by checking for gaps of 3 CPU cores, and it now uses checked subtraction to avoid the prior crash.
=> fix(power): ensure that xeon cpus with cpu gaps are not detected as p/e compatible

.github/workflows/oci-distribution.yml
The OCI distribution workflow contained an unused platform matrix key.
=> fix(workflow): remove reference to unused platform matrix key

crates/daemon/src/reconcile/guest/mod.rs
The original purpose of the runtime reconciler is to handle the case for when things go wrong. In the early days, this was often. Nowadays, this is rare. However, in the event someone does something bad with a domain, it is still helpful to keep tabs on what the true state is. I am proposing switching the reconciler to every 15 seconds. This brings the kratad cpu usage down to 0% with 50 workloads running, spiking to about 30% on my machine every 30 seconds during reconcile. Later in the lifecycle of krata, we can lower this to every few mins.
=> fix(daemon): decrease rate of runtime reconcile

crates/daemon/src/config.rs, crates/daemon/src/lib.rs
This implements a config option to specify an OCI seed, which is the same file format as `docker image save`. This allows you to import seeded images into krata without touching the network.
=> feature(oci): add configuration value for oci seed file

crates/daemon/src/lib.rs
The hypercall to set the power management policies fail under L1 hypervisor.  Need to lab on EC2 to figure out why.
=> chore(powermgmt): disable for now as a hackfix

crates/runtime/src/launch.rs
PCI devices in the request should indicate use of IOMMU, otherwise disable use of it.
=> fix(runtime): use iommu only if devices are needed

.github/dependabot.yml
Dependabot can separate production and development dependency updates into groups, this is very useful to us.
=> fix(dependabot): separate production and development dependency updates

.github/workflows/check.yml, .github/workflows/client.yml, .github/workflows/nightly.yml, .github/workflows/release-binaries.yml, .github/workflows/release-plz.yml, .github/workflows/server.yml
All Rust GitHub actions have dubious security and practices. Use the built-in rustup instead to avoid these pitfalls.
=> chore(workflows): use rustup directly to not depend on external actions

.github/dependabot.yml
This is probably why dependabot can't find anything.
=> chore(dependabot): look for dockerfiles in images subdirectory

.github/workflows/check.yml, .github/workflows/nightly.yml
Workflows should contain the full platform name.
=> fix(workflows): use full platform name in all names

.github/workflows/release-assets.yml
Tag the latest release as latest during the release-assets workflow, and sign it using cosign.
=> fix(workflows): tag latest version during release-assets workflow

crates/zone/src/init.rs
Mounting procfs with hidepid=1 denies access to procfs directories for processes not accessible by the current user credentials.
=> zone: init: mount /proc with hidepid=1

hack/ci/install-darwin-deps.sh
There is a regression in the rustup formula that has caused cascading problems. This is an emergency PR merge to fix this.
=> fix(workflows): upgrade rustup on darwin as best-effort fix for homebrew regression

crates/daemon/src/idm.rs, crates/krata/src/idm/client.rs, crates/xen/xenstore/src/sys.rs, crates/zone/src/background.rs, crates/zone/src/childwait.rs, crates/zone/src/exec.rs
The IDM decoder for the daemon was discarding packets that were in the same frame as the packet. This adds a loop to fix that bug, ensuring that packets are processed in the buffer as available. In addition, exec has been modified to use the child wait mechanism for exit notifications, preventing the flakiness of the exec. With this change, exec ran in a tight loop for 1 minute. It would barely make it 10 iterations prior to this change.
=> fix(idm): process all idm messages in the same frame and use childwait exit notification for exec (fixes #290)

crates/daemon/src/idm.rs, crates/daemon/src/lib.rs, crates/runtime/src/channel.rs, crates/runtime/src/ip.rs, crates/runtime/src/lib.rs
This change adds debug log lines to make it easier to tell where issues are occuring during startup.
=> chore(o11y): add more debug logs to daemon & runtime

crates/daemon/src/lib.rs, crates/runtime/src/power.rs
Fixes #293 in that it removes the hang.  We are still figuring out why the EACCES is happening.
=> fix(power-trap-eacces): gracefully handle hypercall errors in power management

crates/ctl/src/cli/mod.rs
This allows reuse of kratactl independent from how the client and event streams are opened.
=> cleanup(ctl): move logic for branching ctl run steps into ControlCommands

crates/ctl/src/cli/host/dmesg.rs, crates/ctl/src/cli/host/hv_console.rs, crates/ctl/src/cli/host/mod.rs, crates/daemon/src/control.rs, crates/krata/proto/krata/v1/control.proto, crates/runtime/src/lib.rs, crates/xen/xencall/examples/console_read.rs, crates/xen/xencall/src/lib.rs, crates/xen/xencall/src/sys.rs
Adds `kratactl host hv-console` to read the hypervisor console which contains diagnostic messages.
Closes #328.
=> Add support for reading hypervisor console

crates/daemon/bin/daemon.rs
Trace logging is enabled by default, this is not intentional.
=> fix(daemon): turn off trace logging

crates/ctl/src/cli/host/identify.rs, crates/daemon/src/config.rs, crates/daemon/src/console.rs, crates/daemon/src/control.rs, crates/daemon/src/idm.rs, crates/daemon/src/ip/assignment.rs, crates/daemon/src/lib.rs, crates/daemon/src/reconcile/zone/mod.rs, crates/krata/proto/krata/v1/control.proto, crates/network/src/backend.rs, crates/network/src/hbridge.rs, crates/network/src/lib.rs
This implements allocation of the host IP from the reservation store. The gateway IP is now allocated using an all zero UUID, since it is a fake IP.
=> fix(network): allocate host ip from allocation pool
