edera-dev/krata

- crates/ctl/src/cli/attach.rs
- crates/ctl/src/cli/destroy.rs
- crates/ctl/src/cli/launch.rs
- crates/ctl/src/cli/list.rs
- crates/ctl/src/cli/logs.rs
- crates/ctl/src/cli/mod.rs
- crates/ctl/src/cli/resolve.rs
- crates/ctl/src/cli/watch.rs
add help and about info to commands and arguments in kratactl
> feat(ctl): add help and about to commands and arguments

- .github/workflows/release-binaries.yml
Fix the release binary upload.
> chore(workflows): fix release binary upload

- Cargo.lock
- crates/ctl/src/cli/launch.rs
- crates/ctl/src/cli/pull.rs
- crates/daemon/Cargo.toml
- crates/daemon/src/control.rs
- crates/daemon/src/reconcile/guest.rs
- crates/krata/proto/krata/v1/common.proto
- crates/krata/proto/krata/v1/control.proto
- crates/oci/examples/squashify.rs
- crates/oci/src/assemble.rs
- crates/oci/src/fetch.rs
- crates/oci/src/lib.rs
- crates/oci/src/packer/backend.rs
- crates/oci/src/packer/cache.rs
- crates/oci/src/packer/mod.rs
- crates/oci/src/packer/service.rs
- crates/oci/src/progress.rs
- crates/oci/src/registry.rs
- crates/oci/src/schema.rs
- crates/runtime/src/cfgblk.rs
- crates/runtime/src/launch.rs
- bit-perfect disk storage for config and manifest
- oci tar format for storage
- support for concurrent image pulls. this means that when two separate RPC clients request the same image, the packer will pack only one image and broker progress between them.
> feat: oci tar format, bit-perfect disk storage for config and manifest, concurrent image pulls

- crates/ctl/src/cli/launch.rs
- crates/ctl/src/cli/pull.rs
- crates/ctl/src/pull.rs
- crates/daemon/src/control.rs
- crates/daemon/src/lib.rs
- crates/daemon/src/oci.rs
- crates/krata/proto/krata/v1/control.proto
- crates/oci/examples/squashify.rs
- crates/oci/src/assemble.rs
- crates/oci/src/fetch.rs
- crates/oci/src/name.rs
- crates/oci/src/packer/backend.rs
- crates/oci/src/packer/cache.rs
- crates/oci/src/packer/mod.rs
- crates/oci/src/packer/service.rs
- crates/oci/src/progress.rs
- crates/oci/src/registry.rs
- crates/oci/src/vfs.rs
- reimplement oci progress indication protocol
- implement on-disk index for caches images
- utilize rw-lock on in-memory index for concurrent reads
> feat: oci concurrency improvements

- crates/runtime/src/launch.rs
- crates/xen/xencall/src/sys.rs
- crates/xen/xenclient/examples/boot.rs
- crates/xen/xenclient/src/lib.rs
- crates/xen/xenclient/src/tx.rs
- crates/xen/xenplatform/src/boot.rs
- crates/xen/xenplatform/src/domain.rs
- crates/xen/xenplatform/src/lib.rs
- crates/xen/xenplatform/src/x86pv.rs
This change also moves domain creation to xenplatform.
> chore(xen): move device creation into transaction interface

- crates/xen/xencall/Cargo.toml
- crates/xen/xencall/examples/power_management.rs
- crates/xen/xencall/src/error.rs
- crates/xen/xencall/src/lib.rs
- crates/xen/xencall/src/sys.rs
Implements power management APIs to allow higher performance.
> feature(xen): implement power management operations

- CONTRIBUTING.md
Added a period at the end of the list item for consistency with the rest of the style.
> Add period for consistency in list item in contributing.md

- crates/daemon/src/lib.rs
The default policy enables performance mode and SMT.
> feature(daemon): set an initial power management policy

- .github/workflows/check.yml
The existing workflow is evaluating the output as a command (scary), it should just output.
> fix(workflow): format check should print output but not error

- .github/workflows/nightly.yml
- .github/workflows/release-assets.yml
- hack/ci/install-linux-deps.sh
This attempts to detect cross-compilation to know whether to install cross-rs, pins cross-rs to a specific commit, installs fpm only when needed, and pins the fpm version.
> chore(workflows): make builds faster by only installing necessary tools

- crates/zone/src/background.rs
- crates/zone/src/childwait.rs
Bug #304 is due to a waitpid loop blocking the IDM bus, this fixes that by using the root receiver which always has perfect replay while also pausing the waitpid loop for 100 microseconds after an error to prevent channel flooding.
> fix(zone): waitpid should be limited when no child processes exist (fixes #304)

- Cargo.lock
- crates/ctl/src/cli/zone/attach.rs
- crates/ctl/src/cli/zone/launch.rs
- crates/ctl/src/cli/zone/logs.rs
- crates/ctl/src/console.rs
- crates/daemon/src/idm.rs
- crates/krata/src/idm/client.rs
- crates/runtime/src/channel.rs
- crates/runtime/src/ip.rs
- crates/runtime/src/power.rs
- crates/xen/xenevtchn/Cargo.toml
- crates/xen/xenevtchn/examples/simple.rs
- crates/xen/xenevtchn/src/error.rs
- crates/xen/xenevtchn/src/lib.rs
- crates/xen/xenevtchn/src/raw.rs
- crates/xen/xenstore/src/bus.rs
This PR implements a new packet processing algorithm and reworks the event channel library.
> fix(idm): reimplement packet processing algorithm

- crates/ctl/src/cli/zone/launch.rs
- crates/ctl/src/cli/zone/mod.rs
- crates/ctl/src/cli/zone/update_resources.rs
- crates/daemon/src/control.rs
- crates/daemon/src/event.rs
- crates/daemon/src/reconcile/zone/create.rs
- crates/daemon/src/reconcile/zone/mod.rs
- crates/krata/proto/krata/v1/common.proto
- crates/krata/proto/krata/v1/control.proto
- crates/runtime/src/launch.rs
- crates/runtime/src/lib.rs
- crates/xen/xenclient/examples/boot.rs
- crates/xen/xenclient/src/tx.rs
- crates/xen/xenplatform/src/boot.rs
- crates/xen/xenplatform/src/domain.rs
This PR implements dynamic resource allocation according to an UpdateZoneResources RPC. vCPUs are in this API but are not dynamically adjusted yet. A follow up PR will make that change. Hotplugging CPUs is something that needs lots of testing.
> feature(krata): dynamic resource allocation (closes #298)

- doc/admin-guide/custom-kernels.md
> chore(document-custom-kernels): Add initial documentation on custom kernels

- crates/ctl/src/cli/zone/launch.rs
- crates/ctl/src/cli/zone/update_resources.rs
- crates/daemon/src/control.rs
- crates/daemon/src/reconcile/zone/create.rs
- crates/krata/proto/krata/v1/common.proto
- crates/runtime/src/launch.rs
- crates/runtime/src/lib.rs
- crates/xen/xenclient/examples/boot.rs
- crates/xen/xenclient/src/tx.rs
- crates/xen/xenplatform/src/domain.rs
This implements what is needed for basic CPU hotplugging. The init still needs to initialize CPUs in /sys/devices/system/cpu, and in tests, there is still some problems. However, this change is still very valuable.
> feature(krata): first pass on cpu hotplug support

- crates/runtime/src/lib.rs
> feature(xen-preflight): test for hypervisor presence explicitly and error if missing

- .github/workflows/check.yml
- crates/ctl/src/cli/host/hv_console.rs
- crates/ctl/src/cli/host/mod.rs
- crates/ctl/src/cli/mod.rs
- crates/ctl/src/cli/zone/launch.rs
- crates/ctl/src/cli/zone/mod.rs
- crates/daemon/src/control.rs
- crates/daemon/src/reconcile/zone/create.rs
- crates/krata/proto/krata/v1/common.proto
- crates/runtime/src/launch.rs
- crates/runtime/src/lib.rs
- crates/xen/xencall/examples/console_read.rs
- crates/xen/xencall/src/lib.rs
Implements --kernel-cmdline-append and --kernel-verbose on launch.
> feature(zone): kernel command line control on launch

- crates/ctl/src/cli/host/status.rs
- crates/daemon/src/control/get_host_status.rs
- crates/daemon/src/control/mod.rs
- crates/krata/proto/krata/v1/control.proto
- crates/network/src/lib.rs
This RPC didn't match the previous style.
> fix(rpc): rename HostStatus to GetHostStatus

- crates/ctl/src/cli/zone/exec.rs
- crates/ctl/src/console.rs
- crates/daemon/src/control/exec_inside_zone.rs
- crates/krata/proto/krata/idm/internal.proto
- crates/krata/proto/krata/v1/common.proto
- crates/krata/proto/krata/v1/control.proto
- crates/zone/src/exec.rs
This implements terminal resize support in kratactl zone exec.
> feature(zone-exec): implement terminal resize support

- doc/admin-guide/custom-kernels.md
- hack/kernel/fetch.sh
This uses linux-kernel-oci images instead of kernels.
> feature(kernel): switch to linux-kernel-oci images

- README.md
- technical-overview.md
added a technical overview and updated the readme
> added a technical overview and added a link in the readme
